# frontend 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: sjoh0704/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
# api gate way
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template: 
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: api-gateway-container
        image: sjoh0704/apigateway
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: ClusterIP

---
# user-api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-server
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template: 
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-api-container
        image: sjoh0704/user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name:  user-api-service
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: ClusterIP


---
# product-api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-server
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template: 
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-api-container
        image: sjoh0704/product-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name:  product-api-service
spec:
  selector:
    app: product
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: ClusterIP