
  
---
# db-service
apiVersion: v1
kind: Service
metadata:
  name: mysql-user-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    db: mysql-user
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    db: mysql-product
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    db: mysql-order

---

# database deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql-user
  template:
    metadata:
      labels:
        db: mysql-user
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom: 
        - configMapRef:
            name: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-user-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql-product
  template:
    metadata:
      labels:
        db: mysql-product
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom: 
        - configMapRef:
            name: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-product-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql-order
  template:
    metadata:
      labels:
        db: mysql-order
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom: 
        - configMapRef:
            name: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-order-pvc
---

# persistentvolume 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-user-pvc
  labels:
    db: user
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  nfs:
    path: "/data/mysql-user"
    server: 172.31.6.27
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-product-pvc
  labels:
    db: product
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  nfs:
    path: "/data/mysql-product"
    server: 172.31.6.27
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-order-pv
  labels:
    db: order
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  nfs:
    path: "/data/mysql-order"
    server: 172.31.6.27

---
# persistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-user-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector: 
    matchLabels: 
      db: user
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-product-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector: 
    matchLabels: 
      db: product
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-order-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector: 
    matchLabels: 
      db: order
